name       : haskell-rio-orphans
version    : 0.1.1.0
release    : 1
source     :
    - https://hackage.haskell.org/package/rio-orphans-0.1.1.0/rio-orphans-0.1.1.0.tar.gz : 7e8d2c6df6e7afdbca5b344c6e57c754e2d6b9c0cfb4f00e1df88dad1bd48b4e
license    : MIT
component  : programming.haskell
summary    : Orphan instances for the RIO type in the rio package
description: |
    Orphan instances for the RIO type in the rio package
builddeps  :
    - haskell-cabal-install
    - haskell-monad-logger-devel
    - haskell-rio-devel
rundeps    :
    - devel:
        - haskell-monad-logger-devel
        - haskell-rio-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
